// Projects actions
const LOAD_PROJECTS = 'LOAD_PROJECTS';

// Form actions
const CHANGE_INPUT_NAME = "CHANGE_INPUT_NAME";
const ERROR_INPUT_NAME = "ERROR_INPUT_NAME";
const CHANGE_INPUT_EMAIL = "CHANGE_INPUT_EMAIL";
const ERROR_INPUT_EMAIL = "ERROR_INPUT_EMAIL";
const CHANGE_INPUT_SUBJECT = "CHANGE_INPUT_SUBJECT";
const ERROR_INPUT_SUBJECT = "ERROR_INPUT_SUBJECT";
const CHANGE_INPUT_COMMENT = "CHANGE_INPUT_COMMENT";
const ERROR_INPUT_COMMENT = "ERROR_INPUT_COMMENT";
const CHANGE_COUNTER = "CHANGE_COUNTER";
const CHANGE_FORM_STATUS = "CHANGE_FORM_STATUS";

const actions = {
    LOAD_PROJECTS,
    CHANGE_INPUT_NAME,
    ERROR_INPUT_NAME,
    CHANGE_INPUT_EMAIL,
    ERROR_INPUT_EMAIL,
    CHANGE_INPUT_SUBJECT,
    ERROR_INPUT_SUBJECT,
    CHANGE_INPUT_COMMENT,
    ERROR_INPUT_COMMENT,
    CHANGE_COUNTER,
    CHANGE_FORM_STATUS
};

export default actions;